image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/kll/docker-alpine-base:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/kll/docker-alpine-base:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker run --rm -e LOCAL_USER_ID=`id -u $USER` $CONTAINER_TEST_IMAGE id

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
